# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [--extend-select, I, --fix, ./app]
    # Run the formatter.
    - id: ruff-format
      args: [./app]
- repo: https://github.com/python-poetry/poetry
  rev: 1.6.1
  hooks:
  - id: poetry-check
  - id: poetry-lock
    args: [--no-update]
  - id: poetry-export
    args: [-o, requirements.txt, --without-hashes, --without=dev]
