---
version: "3"

services:
  vocabdemy:
    image: vocabdemy:test
    restart: always
    working_dir: /code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - db
    volumes:
      - ${PWD}/app:/code/app/
    networks:
      - backend
    command:
      - bash
      - -c
      - |
        uvicorn app.main:app --host 0.0.0.0 --reload
        sleep infinity
  db:
    image: postgres:${POSTGRES_VERSION}
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend
  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    restart: on-failure
    links:
      - db:db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
