---
version: "3"

services:
  python:
    image: python:${PYTHON_VERSION}
    restart: always
    working_dir: /code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - ${PWD}/app:/code/app/
      - ${PWD}/requirements.txt:/code/requirements.txt
    command:
      - bash
      - -c
      - |
        pip install -r /code/requirements.txt
        uvicorn app.main:app --host 0.0.0.0 --reload
        sleep infinity

  db:
    image: postgres:${POSTGRES_VERSION}
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  db-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
